### ISSUE TITLE
Developing

### ISSUE THREAD

**Issue by samselikoff** [instructure/ic-tabs#11]
I wanted to open up a PR to bump ic-styled to 0.2.0. 

I tried cloning the repo + running `npm install`, and got this error:

```
npm ERR! Error: version not found: broccoli@0.2.0
npm ERR!     at ~/.nvm/v0.10.31/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (~/.nvm/v0.10.31/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "~/.nvm/v0.10.31/bin/node" "/Users/SamSelikoff/.nvm/v0.10.31/bin/npm" "install" "broccoli@0.2.0"
npm ERR! cwd ~/Projects/ic-tabs
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     ~/Projects/ic-tabs/npm-debug.log
npm ERR! not ok code 0
```

Any tips on how to get this working so I can help out w/development?

**Comment by samheuck** [comment]
I've run into the same issue.

Broccoli has released a lot of changes since ic-tabs started using it. 

The following changes to package.json solve this problem, however, ic-tabs will not build with the new template compiler.

```
//package.json
"broccoli": "^0.13.3",
"broccoli-cli": "0.0.1",
"broccoli-dist-es6-module": "^0.2.1",
"broccoli-ember-hbs-template-compiler": "^1.7.0",
"qunitjs": "~1.14.0"
```
